name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  test:
    uses: hapijs/.github/.github/workflows/ci-module.yml@master
