name: Update check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
    update-check:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4

        - name: Install dependencies
          run: npm install

        - name: Run update list
          run: npm run update-list

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          with:
            title: Update TLDs
            commit-message: 'fix: 🤖 Update TLDs'
            branch: fix/auto-update-tlds
            body: Automated update of TLDs
            labels: bug
